# Generated by Django 4.2.1 on 2023-05-18 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('status', models.CharField(choices=[('OS', 'Orçamento solicitado'), ('EA', 'Em análize'), ('R', 'Realizado'), ('C', 'Cancelado'), ('F', 'Fechado')], default='OS', max_length=2)),
                ('service_tag', models.CharField(choices=[('M', 'Motion design'), ('EI', 'Edição de imagem'), ('EV', 'Edição de vídeo')], max_length=2)),
                ('descricao', tinymce.models.HTMLField()),
                ('file_path', models.CharField(max_length=36)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
